### ISSUE TITLE
Pull Requests failing when they contain CAD changes

### ISSUE THREAD

**Issue by stuartpittaway** [index-machines/index#347]
If a 3rd party submits a P.R. with CAD file changes in it, the GITHUB actions run, but always fail as they attempt to commit the changes, even though the 3rd party doesn't have permission to the main Index repo.

```
remote: Permission to index-machines/index.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/index-machines/index.git/': The requested URL returned error: 403
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
```

**Comment by sphawes** [comment]
Closing this, as it was technically fixed when we removed the CI that tries to commit back to the repo!
